### ISSUE TITLE
I want to build Lnd on ios

### ISSUE THREAD

**Issue by gxhx** [mandelmonkey/lndmobile#1]
I already build lightning.framework，but I have no idea how to use this apis。
can you provide a introduction or a demo？
<img width="857" alt="image" src="https://user-images.githubusercontent.com/13634141/39103441-497e2226-46dd-11e8-8648-a43c5e602f4b.png">

**Comment by mandelmonkey** [comment]
Hi
this repo is not production ready tis really some thing to play around with an experiment with
However I can push up an example xcode sample showing how its used later

**Comment by mandelmonkey** [comment]
heres an example project showing the calls used in objective-c 
https://github.com/mandelmonkey/lndmobile-objc-example

**Comment by gxhx** [comment]
Thanks very very very much !!! 😄
